# Generated by Django 4.2.11 on 2024-03-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('idade', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('endereco', models.CharField(max_length=50)),
                ('termo_responsabilidade', models.BooleanField()),
                ('espaco', models.BooleanField()),
                ('tempo', models.BooleanField()),
                ('ciente_custos', models.BooleanField()),
                ('disposicao_fisica_emocional', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Adotante',
                'verbose_name_plural': 'Adotantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='cadastro_animais',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField(max_length=2)),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=10)),
                ('raca', models.CharField(max_length=20)),
                ('porte', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=10)),
                ('castrado', models.BooleanField(default=False)),
                ('vacinado', models.BooleanField(default=False)),
                ('doencas_existentes', models.TextField(blank=True)),
                ('adotado', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cadastro de animais',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('cargo', models.CharField(choices=[('voluntário', 'Voluntário'), ('cuidador', 'Cuidador'), ('admin', 'Admin')], max_length=15)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='adocao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('termo_aceito', models.BooleanField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.adotante')),
                ('animais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.cadastro_animais')),
            ],
            options={
                'verbose_name': 'Adocao',
                'verbose_name_plural': 'Adocoes',
                'ordering': ['-data'],
            },
        ),
    ]
