# Generated by Django 4.2.11 on 2024-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adotante',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastro_animais',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
