# Generated by Django 4.2.11 on 2024-04-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_adocao_animais_delete_cadastro_animais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='funcionarios',
        ),
    ]
