# Generated by Django 4.2.11 on 2024-04-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_delete_funcionarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adocao',
        ),
    ]
