# Generated by Django 4.2.11 on 2024-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_delete_adocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adotante',
            name='termo_responsabilidade',
            field=models.BooleanField(default=False),
        ),
    ]
